yocto_user:
    resource: "@YoctoUserBundle/Controller/"
    type:     annotation
    prefix:   /

yocto_dashboard:
    resource: "@YoctoDashboardBundle/Controller/"
    type:     annotation
    prefix:   /
