security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:        sha256
            encode_as_base64: false
            iterations:       1

        Yocto\Bundle\UserBundle\Entity\User:
            algorithm:        sha256
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, yocto]

        in_memory:
            memory:
                users:
                    user:  { password: 7240a78ca1e55e76f0f4c6e1183e3edbc95e7b35b0de5a94da690fee8a0502fc, roles: [ 'ROLE_USER' ] }
                    admin: { password: ac6a254f1079b3b085b2a20de651642c0fd6018de89fcbc83a0f01578d623615, roles: [ 'ROLE_ADMIN' ] }

        yocto:
            entity: { class: YoctoUserBundle:User }

    firewalls:

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
#            http_basic:
#                realm: "Yocto Authentication"
            logout:
                path:   /logout
                target: /
            form_login:
                check_path: _login_check
                login_path: _login
            remember_me:
                key:      "%secret%"
                lifetime: 60 #2678400 1 month (31 days) in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER, requires_channel: http }
        #- { path: ^/, roles: ROLE_USER, requires_channel: https }
