<?php

namespace Yocto\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupReository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupReository extends EntityRepository
{
}
