parameters:
    yocto_customer.builder.class:       Yocto\Bundle\LayoutBundle\Menu\Builder
    yocto_customer.bundle:
        name: Customers
        role: ROLE_CUSTOMERS
        uri:        /\/customers/
        route:      default_customers

services:
    yocto_customer.builder:
        class: %yocto_customer.builder.class%
        calls:
            - [setBundle, ["%yocto_customer.bundle%"]]
        tags:
            - { name: kernel.event_listener, event: yocto_layout.find_bundles, method: addBundle }
