parameters:
    yocto_customer.builder.class:       Yocto\Bundle\LayoutBundle\Menu\Builder
    yocto_customer.bundle.name:         Customers
    yocto_customer.bundle.role:         ROLE_CUSTOMERS

services:
    yocto_customer.builder:
        class: %yocto_customer.builder.class%
        calls:
            - [setBundle, ["%yocto_customer.bundle.name%", "%yocto_customer.bundle.role%"]]
        tags:
            - { name: kernel.event_listener, event: yocto_layout.find_bundles, method: addBundle }
