parameters:
    yocto_customer.builder.class:       Yocto\Bundle\LayoutBundle\Menu\Builder
    yocto_customer.icon_builder.class:  Yocto\Bundle\CustomerBundle\Menu\Builder
    yocto_customer.bundle:
        name: Customers
        roles: { view: ROLE_CUSTOMERS, edit: ROLE_CUSTOMERS_EDIT, create: ROLE_CUSTOMERS_CREATE, delete: ROLE_CUSTOMERS_DELETE }
        uri:        /\/customers/
        route:      default_customers
        priority:   1

services:
    yocto_customer.builder:
        class: %yocto_customer.builder.class%
        calls:
            - [setBundle, ["%yocto_customer.bundle%"]]
        tags:
            - { name: kernel.event_listener, event: yocto_layout.find_bundles, method: addBundle }

    yocto_customer.icon_builder:
        class: %yocto_customer.icon_builder.class%
        arguments: ['%yocto_customer.bundle%']
        calls:
            - [setBundle, ["%yocto_customer.bundle%"]]
